<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'category',
'color',
'Date Listed',
'descr',
'EPACity',
'EPAHighway',
'features',
'Horsepower',
'id',
'Make',
'Model',
'Phone #',
'Picture',
'Price',
'UserID',
'YearOfMake',
'zipcode' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'category' => array( 'import_field' ),
'color' => array( 'import_field1' ),
'Date Listed' => array( 'import_field2' ),
'descr' => array( 'import_field3' ),
'EPACity' => array( 'import_field4' ),
'EPAHighway' => array( 'import_field5' ),
'features' => array( 'import_field6' ),
'Horsepower' => array( 'import_field7' ),
'id' => array( 'import_field8' ),
'Make' => array( 'import_field9' ),
'Model' => array( 'import_field10' ),
'Phone #' => array( 'import_field11' ),
'Picture' => array( 'import_field12' ),
'Price' => array( 'import_field13' ),
'UserID' => array( 'import_field14' ),
'YearOfMake' => array( 'import_field15' ),
'zipcode' => array( 'import_field16' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'category',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'color',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Date Listed',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'descr',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'EPACity',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'EPAHighway',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'features',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Horsepower',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'id',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Make',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Model',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Phone #',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Picture',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Price',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'UserID',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'YearOfMake',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'zipcode',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>