<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'hideNumberOfRecords' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'Make' => array( 'totalsType' => '' ),
'Model' => array( 'totalsType' => '' ),
'YearOfMake' => array( 'totalsType' => '' ),
'Picture' => array( 'totalsType' => '' ),
'Horsepower' => array( 'totalsType' => '' ),
'EPACity' => array( 'totalsType' => '' ),
'EPAHighway' => array( 'totalsType' => '' ),
'Price' => array( 'totalsType' => '' ),
'Date Listed' => array( 'totalsType' => '' ),
'Phone #' => array( 'totalsType' => '' ),
'UserID' => array( 'totalsType' => '' ),
'descr' => array( 'totalsType' => '' ),
'color' => array( 'totalsType' => '' ),
'category' => array( 'totalsType' => '' ),
'zipcode' => array( 'totalsType' => '' ),
'features' => array( 'totalsType' => '' ),
'logo' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Picture',
'YearOfMake',
'Make',
'Model',
'Price',
'Horsepower',
'color' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'Make' ),
'filterFields' => array( 'Price',
'Horsepower',
'Make',
'Model' ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'YearOfMake' => array( 'grid_field3' ),
'Make' => array( 'grid_field' ),
'Model' => array( 'grid_field1' ),
'Horsepower' => array( 'grid_field_label4',
'grid_field4' ),
'color' => array( 'grid_field5',
'grid_field_label5' ),
'Picture' => array( 'grid_field6' ),
'Price' => array( 'grid_field2' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'details_found',
'page_size',
'menu2' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel',
'filter_panel' ),
'supertop' => array( 'expand_menu_button',
'expand_menu_button1',
'collapse_button',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'grid' => array( 'grid_edit',
'grid_view',
'grid_field3',
'grid_field',
'grid_field1',
'grid_field_label4',
'grid_field4',
'grid_field5',
'grid_field_label5',
'grid_field6',
'grid_field2' ),
'top' => array(  ) ),
'formXtTags' => array( 'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'details_found' => 'above-grid',
'page_size' => 'above-grid',
'menu2' => 'above-grid',
'pagination' => 'below-grid',
'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'filter_panel' => 'left',
'expand_menu_button' => 'supertop',
'expand_menu_button1' => 'supertop',
'collapse_button' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'grid_edit' => 'grid',
'grid_view' => 'grid',
'grid_field3' => 'grid',
'grid_field' => 'grid',
'grid_field1' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field5' => 'grid',
'grid_field_label5' => 'grid',
'grid_field6' => 'grid',
'grid_field2' => 'grid' ),
'itemLocations' => array( 'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_menu_button1' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'details_found' => array( 'details_found' ),
'page_size' => array( 'page_size' ),
'menu2' => array( 'menu2' ),
'pagination' => array( 'pagination' ),
'grid_edit' => array( 'grid_edit' ),
'grid_view' => array( 'grid_view' ),
'grid_field' => array( 'grid_field3',
'grid_field',
'grid_field1',
'grid_field4',
'grid_field5',
'grid_field6',
'grid_field2' ),
'grid_field_label' => array( 'grid_field_label4',
'grid_field_label5' ),
'advsearch_link' => array( 'advsearch_link' ),
'-' => array( '-' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'filter_panel_field' => array( 'filter_panel_field',
'filter_panel_field1',
'filter_panel_field2',
'filter_panel_field3' ),
'search_panel_field' => array( 'search_panel_field' ),
'simple_search' => array( 'simple_search' ),
'list_options' => array( 'list_options' ),
'loginform_login' => array( 'loginform_login' ),
'username_button' => array( 'username_button' ),
'filter_panel' => array( 'filter_panel' ),
'menu' => array( 'menu' ),
'search_panel' => array( 'search_panel' ),
'expand_menu_button' => array( 'expand_menu_button',
'expand_menu_button1' ),
'collapse_button' => array( 'collapse_button' ),
'logo' => array( 'logo1' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'edit_column',
'view_column' ),
'items' => array( 'grid_edit',
'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_top1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 1 ),
'tags' => array( 'Picture_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'YearOfMake_fieldcolumn',
'Make_fieldcolumn',
'Model_fieldcolumn' ),
'items' => array( 'grid_field3',
'grid_field',
'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 1,
2 ),
'rows' => array( 2 ),
'tags' => array( 'Price_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 3 ),
'tags' => array( 'Horsepower_fieldheadercolumn',
'Horsepower_fieldcolumn',
'color_fieldcolumn',
'color_fieldheadercolumn' ),
'items' => array( 'grid_field_label4',
'grid_field4',
'grid_field5',
'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 5 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 1,
'recsPerRow' => 3,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ),
array( 'id' => 'secondary',
'horizontal' => true ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 2 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c3',
'items' => array( 'menu2' ) ),
'c4' => array( 'model' => 'c4',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel',
'filter_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'expand_menu_button1',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'vertical-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top' ),
array( 'cell' => 'cell_top1' ),
array( 'cell' => 'cell_field5' ) ),
'section' => 'head' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label2',
'colspan' => 3 ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field4',
'colspan' => 2 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_field1',
'colspan' => 3,
'rowspan' => 1 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 3 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array( 'grid_edit',
'grid_view' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3',
'grid_field',
'grid_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'customCSS' => '/* Put  your custom CSS code here */

:host {
  width:70% !important;
}
',
'padding' => array( 'left' => '10px' ),
'field' => 'YearOfMake',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field_label4',
'grid_field4',
'grid_field5',
'grid_field_label5' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'horizontal',
'padding' => array( 'bottom' => '10px' ),
'field' => 'Horsepower',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_top',
'items' => array(  ) ),
'cell_top1' => array( 'model' => 'cell_top',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'align' => 'center',
'padding' => array( 'top' => '0px',
'bottom' => '0px',
'left' => '0px',
'right' => '0px' ),
'field' => 'Picture',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'customCSS' => '/* Put  your custom CSS code here */

:host {
   width:70% !important;
}
',
'align' => 'right',
'padding' => array( 'right' => '10px' ),
'field' => 'Price',
'columnName' => 'field' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 3 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'details_found' => array( 'type' => 'details_found',
'padding' => array( 'top' => '8px' ) ),
'page_size' => array( 'type' => 'page_size' ),
'menu2' => array( 'type' => 'menu2' ),
'pagination' => array( 'type' => 'pagination' ),
'grid_edit' => array( 'type' => 'grid_edit' ),
'grid_view' => array( 'type' => 'grid_view' ),
'grid_field3' => array( 'field' => 'YearOfMake',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'padding' => array( 'left' => '10px' ),
'bold' => true,
'font-size' => '16px',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  color: rgb(24, 53, 88);
  line-height: 20px;
}
' ),
'grid_field' => array( 'field' => 'Make',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true,
'customCSS' => '/* Put  your custom CSS code here */

:host {
  color: rgb(24, 53, 88);
  line-height: 20px;
}
' ),
'grid_field1' => array( 'field' => 'Model',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true,
'customCSS' => '/* Put  your custom CSS code here */

:host {
  color: rgb(24, 53, 88);
  line-height: 20px;
}
' ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'Horsepower',
'label' => array( 'field' => 'Horsepower',
'table' => 'carscars',
'type' => 3 ),
'padding' => array( 'left' => '10px' ),
'color' => '#aab1c7',
'bold' => true ),
'grid_field4' => array( 'field' => 'Horsepower',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'color' => '#aab1c7' ),
'grid_field5' => array( 'field' => 'color',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'color' => '#aab1c7',
'customCSS' => '/* Put  your custom CSS code here */

:host {
 float:right;
}
' ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'color',
'label' => array( 'field' => 'color',
'table' => 'carscars',
'type' => 3 ),
'padding' => array( 'left' => '10px',
'right' => '5px' ),
'color' => '#aab1c7',
'bold' => true,
'customCSS' => '/* Put  your custom CSS code here */

:host {
 float:right;
}
' ),
'grid_field6' => array( 'field' => 'Picture',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'customCSS' => '/* Put  your custom CSS code here */

:host {
  color: red;
}
:host span{
    width: 100%;
    display: block;
}
:host .list_image{
    width:100%;
    height:200px;
    background-size:cover;
    background-position:center center;
}' ),
'grid_field2' => array( 'field' => 'Price',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'padding' => array( 'left' => '10px' ),
'font-size' => '20px',
'color' => '#2fa4e7' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-' => array( 'type' => '-' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'filter_panel_field' => array( 'field' => 'Price',
'type' => 'filter_panel_field' ),
'filter_panel_field1' => array( 'field' => 'Horsepower',
'type' => 'filter_panel_field' ),
'filter_panel_field2' => array( 'field' => 'Make',
'type' => 'filter_panel_field' ),
'filter_panel_field3' => array( 'field' => 'Model',
'type' => 'filter_panel_field' ),
'search_panel_field' => array( 'field' => 'Make',
'type' => 'search_panel_field' ),
'simple_search' => array( 'type' => 'simple_search' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'-' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link' ) ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array( 'filter_panel_field',
'filter_panel_field1',
'filter_panel_field2',
'filter_panel_field3' ) ),
'menu' => array( 'type' => 'menu' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field' ) ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'logo1' => array( 'type' => 'logo' ),
'expand_menu_button1' => array( 'type' => 'expand_menu_button' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>