<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'color',
'Horsepower',
'category',
'Picture',
'EPACity',
'EPAHighway',
'zipcode',
'Phone #',
'descr',
'features',
'Price',
'Make',
'Model',
'YearOfMake',
'Date Listed' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'color' => array( 'integrated_edit_field1' ),
'Horsepower' => array( 'integrated_edit_field7' ),
'category' => array( 'integrated_edit_field' ),
'Picture' => array( 'integrated_edit_field12' ),
'EPACity' => array( 'integrated_edit_field4' ),
'EPAHighway' => array( 'integrated_edit_field5' ),
'zipcode' => array( 'integrated_edit_field16' ),
'Phone #' => array( 'integrated_edit_field11' ),
'descr' => array( 'integrated_edit_field3' ),
'features' => array( 'integrated_edit_field6' ),
'Price' => array( 'integrated_edit_field13' ),
'Make' => array( 'integrated_edit_field9' ),
'Model' => array( 'integrated_edit_field10' ),
'YearOfMake' => array( 'integrated_edit_field15' ),
'Date Listed' => array( 'Date_Listed' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'loginform_login',
'username_button' ),
'top' => array( 'view_back_list' ),
'above-grid' => array(  ),
'below-grid' => array(  ),
'grid' => array( 'integrated_edit_field3',
'integrated_edit_field16',
'Date_Listed',
'integrated_edit_field13',
'custom_button',
'integrated_edit_field11',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field15',
'integrated_edit_field1',
'integrated_edit_field7',
'integrated_edit_field',
'integrated_edit_field5',
'integrated_edit_field4',
'integrated_edit_field12',
'integrated_edit_field6' ) ),
'formXtTags' => array( 'top' => array( 'back_button' ),
'above-grid' => array(  ),
'below-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'view_back_list' => 'top',
'integrated_edit_field3' => 'grid',
'integrated_edit_field16' => 'grid',
'Date_Listed' => 'grid',
'integrated_edit_field13' => 'grid',
'custom_button' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field6' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'Date_Listed' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'custom_button' => array( 'location' => 'grid',
'cellId' => 'c13' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c14' ) ),
'itemVisiblity' => array( 'username_button' => 3,
'loginform_login' => 3 ) ),
'itemsByType' => array( 'integrated_edit_field' => array( 'integrated_edit_field1',
'integrated_edit_field7',
'integrated_edit_field',
'integrated_edit_field12',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field16',
'integrated_edit_field11',
'integrated_edit_field3',
'integrated_edit_field6',
'Date_Listed' ),
'edit_field' => array( 'integrated_edit_field13',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field15' ),
'custom_button' => array( 'custom_button' ),
'logo' => array( 'logo' ),
'view_back_list' => array( 'view_back_list' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 0,
1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1',
'integrated_edit_field7',
'integrated_edit_field',
'integrated_edit_field5',
'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 1 ),
'rows' => array( 5,
6,
7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'Date_Listed' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 8 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => true,
'customButtons' => array( 'Get_a_quote' ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'Get_a_quote' ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2',
'colspan' => 1 ),
array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'logo' ) ),
'c4' => array( 'model' => 'c3',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'view_back_list' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c2',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c5',
'rowspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c13',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3',
'rowspan' => 1 ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c14',
'rowspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12',
'rowspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7',
'colspan' => 1,
'rowspan' => 1 ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field3' ),
'orientation' => 'horizontal' ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field16' ),
'align' => 'left',
'orientation' => 'horizontal' ),
'c7' => array( 'model' => 'c3',
'items' => array( 'Date_Listed' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field13' ),
'orientation' => 'horizontal',
'cellpadding' => array( 'top' => '50px' ),
'align' => 'left',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  padding-top:7px;
}
' ),
'c13' => array( 'model' => 'c3',
'items' => array( 'custom_button' ),
'orientation' => 'vertical',
'cellpadding' => array( 'top' => '50px' ),
'align' => 'left',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  padding-left:10px;
}
' ),
'c11' => array( 'model' => 'c3',
'items' => array(  ),
'align' => 'left' ),
'c12' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field11' ),
'align' => 'left',
'orientation' => 'horizontal' ),
'c1' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field15' ),
'align' => 'left',
'orientation' => 'horizontal' ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1',
'integrated_edit_field7',
'integrated_edit_field',
'integrated_edit_field5',
'integrated_edit_field4' ),
'align' => 'left',
'padding' => array( 'top' => '15px' ) ),
'c10' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field12' ),
'align' => 'left' ),
'c14' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field6' ),
'align' => 'left' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'integrated_edit_field1' => array( 'field' => 'color',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'Horsepower',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field' => array( 'field' => 'category',
'type' => 'integrated_edit_field',
'orientation' => 0,
'joined' => true,
'separated' => false ),
'integrated_edit_field12' => array( 'field' => 'Picture',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'Picture',
'table' => 'carscars',
'type' => 3 ) ),
'integrated_edit_field4' => array( 'field' => 'EPACity',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'EPAHighway',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'zipcode',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'Phone #',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'descr',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'features',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'Price',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'padding' => array( 'left' => '10px',
'top' => '10px' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
  margin-left:0 !important;
}
',
'font-size' => '22px',
'bold' => true ),
'custom_button' => array( 'type' => 'custom_button',
'eventId' => 'Get_a_quote',
'label' => array( 'text' => 'Get a quote',
'type' => 0 ),
'buttonSize' => 'xtra-small',
'buttonStyle' => 'primary',
'padding' => array( 'left' => '10px',
'top' => '10px' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
 margin-left:0 !important;
}
' ),
'integrated_edit_field9' => array( 'field' => 'Make',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'padding' => array( 'left' => '10px' ),
'font-size' => '20px',
'customCSS' => '/* Put  your custom CSS code here */

:host {
    padding-right:5px !important;
}
' ),
'integrated_edit_field10' => array( 'field' => 'Model',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'font-size' => '20px',
'customCSS' => '/* Put  your custom CSS code here */

:host {
    padding-right:5px !important;
    padding-left:0px !important;
}
' ),
'integrated_edit_field15' => array( 'field' => 'YearOfMake',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'font-size' => '20px',
'customCSS' => '/* Put  your custom CSS code here */

:host {
    padding-right:5px !important;
    padding-left:0px !important;
}
' ),
'logo' => array( 'type' => 'logo' ),
'Date_Listed' => array( 'field' => 'Date Listed',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'view_back_list' => array( 'type' => 'view_back_list',
'buttonStyle' => 'link-button',
'icon' => array( 'glyph' => 'home' ),
'label' => array( 'type' => 0,
'text' => 'Back to cars list' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
  background-color: #f5f5f5;
  border-radius: 4px;
  text-align:left;
  
}
:host .glyphicon-home{
    margin-right: 7px;
}' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ) ),
'dbProps' => array(  ),
'version' => 14,
'pageAlign' => 'center',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>